export default [
  'white-secondary',
  'base',
  'base-secondary',
  'gray',
  'gray-secondary',
  'dark-gray',
  'dark-gray-secondary',
  'blue',
  'blue-secondary',
  'dark-blue',
  'dark-blue-secondary',
  'green',
  'green-secondary',
  'orange',
  'orange-secondary',
  'red',
  'red-secondary',
  'yellow',
  'yellow-secondary',
]

